sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - env: TOXENV=py27-pytest29
      python: 2.7
    - env: TOXENV=py27-pytest31
      python: 2.7
    - env: TOXENV=py27-pytestmaster
      python: 2.7
    - env: TOXENV=py27-pytestfeatures
      python: 2.7

    - env: TOXENV=py34-pytest29
      python: 3.4
    - env: TOXENV=py35-pytest29
      python: 3.5
    - env: TOXENV=py36-pytest31
      python: 3.6
    - env: TOXENV=py36-pytest32
      python: 3.6
    - env: TOXENV=py36-pytest33
      python: 3.6
    - env: TOXENV=py36-pytestmaster
      python: 3.6
    - env: TOXENV=py36-pytestfeatures
      python: 3.6
    - env: TOXENV=py36-pytest32-xdist
      python: 3.6

install:
  - pip install tox

script:
  - tox
