environment:
  matrix:
  - PYTHON: "C:\\Python36-x64"
  - PYTHON: "C:\\Python27-x64"

install:
# symlink python from a directory with a space
- "mklink /d \"C:\\Program Files\\Python\" %PYTHON%"
- "SET PYTHON=\"C:\\Program Files\\Python\""
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- "python -m pip install tox"


before_build:
- python -m pip install wheel

build_script:
- python -m setup bdist_wheel

test_script:
- tox -e python

version: '{build}'

artifacts:
- path: dist\*
